
    graph TD;
        e1[Start] --> e2[Process 1];
        e2 --> e3[Process 2];
        e3 --> e4[Process 3];
        e4 --> e5[End];
    

    classDef active fill:#ff0000,stroke:#000,color:#fff;
    